preserve_hierarchy: true

files:
  - source: /src/content/pages/en/*.md
    translation: /src/content/pages/%two_letters_code%/%original_file_name%
  - source: /src/content/i18n/en.json
    translation: /src/content/i18n/%two_letters_code%.json
